// Generated by scripts/email-assets/build.tsx. Do not edit by hand.
// Images live in public/email/; sizes are display pixels (the PNGs are 2x).

export const EMAIL_LOGO = {"width":200,"height":36} as const;
export const EMAIL_SQUIGGLE = {"width":84,"height":10} as const;
export const EMAIL_CREST = {"width":48,"height":51} as const;
export const EMAIL_NAME_HEIGHT = 25;

/** Per college slug: whether a crest PNG exists, and the name PNG's width. */
export const EMAIL_COLLEGE_ASSETS: Record<string, { crest: boolean; nameWidth: number }> = {
  "all-souls": {
    "crest": true,
    "nameWidth": 89
  },
  "balliol": {
    "crest": true,
    "nameWidth": 74
  },
  "blackfriars": {
    "crest": true,
    "nameWidth": 114
  },
  "brasenose": {
    "crest": true,
    "nameWidth": 94
  },
  "campion-hall": {
    "crest": true,
    "nameWidth": 127
  },
  "christ-church": {
    "crest": true,
    "nameWidth": 131
  },
  "corpus-christi": {
    "crest": true,
    "nameWidth": 139
  },
  "exeter": {
    "crest": true,
    "nameWidth": 63
  },
  "green-templeton": {
    "crest": true,
    "nameWidth": 157
  },
  "harris-manchester": {
    "crest": true,
    "nameWidth": 177
  },
  "hertford": {
    "crest": true,
    "nameWidth": 85
  },
  "jesus": {
    "crest": true,
    "nameWidth": 54
  },
  "keble": {
    "crest": true,
    "nameWidth": 53
  },
  "kellogg": {
    "crest": true,
    "nameWidth": 78
  },
  "lady-margaret-hall": {
    "crest": true,
    "nameWidth": 186
  },
  "linacre": {
    "crest": true,
    "nameWidth": 73
  },
  "lincoln": {
    "crest": true,
    "nameWidth": 73
  },
  "magdalen": {
    "crest": true,
    "nameWidth": 92
  },
  "mansfield": {
    "crest": true,
    "nameWidth": 97
  },
  "merton": {
    "crest": true,
    "nameWidth": 66
  },
  "new-college": {
    "crest": true,
    "nameWidth": 123
  },
  "nuffield": {
    "crest": true,
    "nameWidth": 84
  },
  "oriel": {
    "crest": true,
    "nameWidth": 54
  },
  "pembroke": {
    "crest": true,
    "nameWidth": 88
  },
  "queens": {
    "crest": true,
    "nameWidth": 70
  },
  "regents-park": {
    "crest": true,
    "nameWidth": 126
  },
  "reuben": {
    "crest": true,
    "nameWidth": 65
  },
  "somerville": {
    "crest": true,
    "nameWidth": 107
  },
  "st-annes": {
    "crest": true,
    "nameWidth": 85
  },
  "st-antonys": {
    "crest": true,
    "nameWidth": 103
  },
  "st-catherines": {
    "crest": true,
    "nameWidth": 134
  },
  "st-cross": {
    "crest": true,
    "nameWidth": 78
  },
  "st-edmund-hall": {
    "crest": true,
    "nameWidth": 146
  },
  "st-hildas": {
    "crest": true,
    "nameWidth": 94
  },
  "st-hughs": {
    "crest": true,
    "nameWidth": 86
  },
  "st-johns": {
    "crest": true,
    "nameWidth": 84
  },
  "st-peters": {
    "crest": true,
    "nameWidth": 90
  },
  "trinity": {
    "crest": true,
    "nameWidth": 71
  },
  "university": {
    "crest": true,
    "nameWidth": 103
  },
  "wadham": {
    "crest": true,
    "nameWidth": 77
  },
  "wolfson": {
    "crest": true,
    "nameWidth": 82
  },
  "worcester": {
    "crest": true,
    "nameWidth": 101
  },
  "wycliffe-hall": {
    "crest": true,
    "nameWidth": 139
  }
};
